sudo: false
git:
  depth: 1
language: node_js
cache: yarn
node_js:
  - stable
  - '0'
after_script:
  - npm install istanbul-coveralls@1
  - npm run-script coverage
  - node node_modules/.bin/istanbul-coveralls
